-- 0001_init.sql — Dully Onboarding initial schema
-- Run this in the Supabase SQL editor (Dashboard → SQL Editor → New query → paste → Run),
-- or via the Supabase CLI once it's installed.
--
-- Mirrors onboarding/BACKEND_SPEC.md: four first-class columns + a loose `sections` jsonb blob
-- whose shape is owned by the frontend.

-- ============ Tables ============

create table if not exists public.onboardings (
  id            text primary key,                 -- cryptographically-random token (>=24 chars), generated by the app
  customer_name text not null,
  created_at    timestamptz not null default now(),
  completed_at  timestamptz,
  sections      jsonb not null default '{}'::jsonb
);

create table if not exists public.onboarding_files (
  id             uuid primary key default gen_random_uuid(),
  onboarding_id  text not null references public.onboardings(id) on delete cascade,
  section        text not null,        -- e.g. 'employees'
  field          text not null,        -- e.g. 'csvFile' | 'contractFiles'
  file_name      text not null,
  storage_path   text not null,        -- path inside the 'onboarding-files' bucket
  content_type   text,
  size_bytes     bigint,
  uploaded_at    timestamptz not null default now()
);

create index if not exists onboarding_files_onboarding_id_idx
  on public.onboarding_files (onboarding_id);

-- ============ Row Level Security ============
-- Deny-by-default. ALL database access goes through Next.js server Route Handlers
-- using the SERVICE ROLE key (which bypasses RLS). We create NO anon/public policies,
-- so even a leaked anon key cannot read or write these tables.

alter table public.onboardings      enable row level security;
alter table public.onboarding_files enable row level security;
-- (intentionally no policies — service-role-only access)

-- ============ Storage bucket (private) ============
-- Files (employee CSV, Word contracts, budget, supplier lists) live here.
-- Private bucket → access only via short-lived signed URLs minted server-side.

insert into storage.buckets (id, name, public)
values ('onboarding-files', 'onboarding-files', false)
on conflict (id) do nothing;
-- No storage RLS policies → service role only. Never make this bucket public.
